# Render Blueprint Configuration (Infrastructure as Code)
# Este archivo le dice a Render.com exactamente cómo debe servir tu página sin que tengas que tocar nada manual.

services:
  - type: web
    name: growing-along-web
    env: static
    # Al ser Vanilla HTML, no necesitamos compilar nada.
    buildCommand: ""
    # Renderizará todo lo que esté en la raíz de la carpeta (donde están tus archivos .html)
    staticPublishPath: .
    # Si quisieras añadir reglas de ruteo como quitar el ".html" del texto en el futuro, esto forzará que todos carguen correctamente.
    routes:
      - type: rewrite
        source: /about
        destination: /about.html
      - type: rewrite
        source: /services
        destination: /services.html
      - type: rewrite
        source: /parents
        destination: /parents.html
      - type: rewrite
        source: /contact
        destination: /contact.html
